CREATE TABLE Usuario (
    ID_Usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Cedula VARCHAR2(20) UNIQUE NOT NULL,
    Nombre VARCHAR2(50) NOT NULL,
    Apellidos VARCHAR2(100) NOT NULL,
    Numero_Telefonico VARCHAR2(20)
);

CREATE TABLE Editorial (
    ID_Editorial NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(100) UNIQUE NOT NULL
);

CREATE TABLE Autor (
    ID_Autor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Apellidos VARCHAR2(100) NOT NULL
);

CREATE TABLE Genero (
    ID_Genero NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nombre VARCHAR2(50) NOT NULL,
    Descripcion VARCHAR2(255)
);

CREATE TABLE Libros (
    ID_Libro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Titulo VARCHAR2(200) NOT NULL,
    ISBN VARCHAR2(20) UNIQUE NOT NULL,
    Edad_Recomendada VARCHAR2(10), --Lo cambié a VARCHAR2 para poder poner 3-5, +18, etc 
    Inventario NUMBER NOT NULL,
    ID_Editorial NUMBER,
    FOREIGN KEY (ID_Editorial) REFERENCES Editorial(ID_Editorial)
);

CREATE TABLE Reservas (
    ID_Reserva NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Fecha_Reserva DATE NOT NULL,
    Fecha_Devolucion DATE NOT NULL,
    ID_Usuario NUMBER NOT NULL,
    FOREIGN KEY (ID_Usuario) REFERENCES Usuario(ID_Usuario)
);

-- Tablas intermedias 
CREATE TABLE Libro_Reserva(
    ID_Reserva NUMBER NOT NULL,
    ID_Libro NUMBER NOT NULL,
    FOREIGN KEY (ID_Reserva) REFERENCES Reservas(ID_Reserva),
    FOREIGN KEY (ID_Libro) REFERENCES Libros(ID_Libro),
    PRIMARY KEY (ID_Reserva, ID_Libro)
);

CREATE TABLE Autor_Libro(
    ID_Autor NUMBER NOT NULL,
    ID_Libro NUMBER NOT NULL,
    FOREIGN KEY (ID_Autor) REFERENCES Autor(ID_Autor),
    FOREIGN KEY (ID_Libro) REFERENCES Libros(ID_Libro),
    PRIMARY KEY (ID_Autor, ID_Libro)
);

CREATE TABLE Genero_Libro(
    ID_Genero NUMBER NOT NULL,
    ID_Libro NUMBER NOT NULL,
    FOREIGN KEY (ID_Genero) REFERENCES Genero(ID_Genero),
    FOREIGN KEY (ID_Libro) REFERENCES Libros(ID_Libro),
    PRIMARY KEY (ID_Genero, ID_Libro)
);


/*
--Trigger para manejar inventario al añadir o eliminar libros de a reserva
CREATE OR REPLACE TRIGGER t_actualizar_invetario
    BEFORE INSERT OR DELETE
    ON Libro_Reserva
    FOR EACH ROW
DECLARE
    v_inventario_actual INTEGER;
    v_titulo VARCHAR(100);

    BEGIN
        IF inserting THEN
            SELECT Inventario, Titulo INTO v_inventario_actual, v_titulo
            FROM Libros
            WHERE ID_Libro = :NEW.ID_Libro;

            IF v_inventario_actual <= 0 THEN
                RAISE_APPLICATION_ERROR(-20001, 'Error 20001: No se cuenta con inventario del título' || v_titulo);

            ELSE
            UPDATE Libros
                SET Inventario = Inventario - 1
            WHERE ID_Libro  = :NEW.ID_Libro;
            END IF;

        ELSIF deleting THEN
            UPDATE Libros
                SET Inventario = Inventario + 1
            WHERE ID_Libro = :OLD.ID_Libro;
        END IF;
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'Error 20002: Error al buscar el libro con el ID ' || :NEW.ID_Libro);
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20000, 'Error 20000: Error inesperado');    

    END;
/
*/